### ISSUE TITLE
Nav Drawer Disables screen but doesn't always re-enable screen

### ISSUE THREAD

**Issue by GoBig87** [GoBig87/code-jam-6#26] opened 2020-01-24 18:06 UTC
The disables the screen behind it because there is a  bug with scroll views that messes up the button presses on the nav drawer.  To get around this bug I disabled the screen behind it.  The screen needs to be re enabled in all cases not just the toggle behavior.

**Comment by foosballa91** [comment] 2020-01-24 18:33
Duplicate of 22#

**Closed** 2020-01-24 18:32 UTC
